# Light node image with yarn installed
FROM node:13.12.0-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

EXPOSE 8080

COPY package.json ./
COPY yarn.lock ./

RUN yarn install --frozen-lockfile --quiet

COPY . .

CMD ["yarn", "dev"]
