version: '3'

services:
  api:
    environment:
      - PORT=8080
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8080:8080'
